name: Terraform Lint

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        run: |
          echo "Hello-world"
  init:
    runs-on: ubuntu-latest
    steps:
      - uses: hashicorp/setup-terraform@v2
    
      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: true
      
      - name: Terraform Init
        id: init
        run: terraform init
  