name: Terraform Check

on: push

defaults:
  run:
    working-directory: ${{ env.tf_actions_working_dir }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        run: |
          ls -al
          pwd
  init:
    runs-on: ubuntu-latest
    steps:
      - uses: hashicorp/setup-terraform@v2
    
      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: true
      
      - name: Terraform Init
        id: init
        run: terraform init
  